# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2022-03-22T07:54:56+00:00

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass
