apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Fio
metadata:
  name: disk-fio
spec:
  image:
    name: xridge/fio:3.13
    pullPolicy: IfNotPresent

  cmdLineArgs: --name=randwrite --iodepth=1 --rw=randwrite --bs=4m --size=256M

  volume:
    volumeSource:
      emptyDir: {}