kind: Cluster
name: benchmark-operator
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# the control plane node config
- role: control-plane
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
  extraPortMappings:
  - containerPort: 31313
    hostPort: 8000
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 30090
    hostPort: 9090
    listenAddress: "127.0.0.1"
    protocol: TCP
# the three workers
- role: worker
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
- role: worker
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c