KUBERNETES_SERVER = "https://localhost:16443"
KUBERNETES_CA_PATH = "/var/snap/microk8s/current/certs/ca.crt"
KUBERNETES_USERNAME = "admin"
KUBERNETES_AUTH_SCHEME = "Bearer"
KUBERNETES_TOKEN = "<Your Token Here>"
